fix: include order when building with -DCXXOPTS_USE_UNICODE
This change fixes a bizarre build failure that happens when trying to
build docling-parse with system cxxopts that define `CXXOPTS_USE_UNICODE`.

The error causes implicit conversion from boolean types to fail, causing
errors like this:

```
In file included from /build/docling_parse-5.7.0/src/parse.h:44,
                 from /build/docling_parse-5.7.0/app/parse_fonts.cpp:17:
/build/docling_parse-5.7.0/src/parse/config.h: In member function ‘nlohmann::json_abi_v3_12_0::json pdflib::decode_config::to_json() const’:
/build/docling_parse-5.7.0/src/parse/config.h:60:58: error: no matching function for call to ‘nlohmann::json_abi_v3_12_0::basic_json<>::basic_json(const bool&)’
   60 |     j["do_sanitization"] = nlohmann::json(do_sanitization);
      |                                                          ^
```

Signed-off-by: Attila Oláh <attila@dorn.haus>